### ISSUE TITLE
필요한 데이터 조사

### ISSUE THREAD

**Issue by Shinhyeonbin** [ProjectEResume/ecomarket#1]
Eco market의 프로젝트의 진행가능성을 판단하기 위한 자료조사

필요 사항
* 제품명
* 기업이름
* 브랜드

**Comment by Taehwan2** [comment]
[HwanServer.txt](https://github.com/ProjectEResume/ecomarket/files/10715623/HwanServer.txt)

**Comment by Taehwan2** [comment]
일단 각 특징과 녹색제품 분야종류 -> 특징-> 이런부분 정리해서 올렸슴돠

**Comment by Shinhyeonbin** [comment]
파일 document에 올렸슴돠
* 태환이 것도 같이 올렸슴돠
